### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by slsters** [flashlxy/PyMICAPS#11]
解决了python版本各种包的问题，还是unsupported operand type(s) for +: 'NoneType' and 'float'，哎。您说的运行程序 python main.py config.xml是什么意思呢？我用python.exe运行不了这个命令，pycharm运行main.py也会报错就是这个unsupported operand type(s) for +: 'NoneType' and 'float'。
我只是个小白，望您指点。

**Comment by flashlxy** [comment]
错误信息不详细，贴出具体错误信息
