### ISSUE TITLE
运行报了这个错误，小白不懂如何解决

### ISSUE THREAD

**Issue by Kaitodes** [flashlxy/PyMICAPS#12]
'utf8' codec can't decode byte 0xba in position 0: invalid start byte

**Comment by MaskBoy** [comment]
> 'utf8'编解码器无法解码位置0中的字节0xba：无效的起始字节

maskout.py  -->  shapefile.Reader(shpfile, encoding='GB2312')指定一下字符集 改完之后完全不一样的图 还在弄
