### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [flashlxy/PyMICAPS#14]
python环境3.7
报错信息
$ python main.py config.xml
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by flashlxy** [comment]
仔细查看项目环境，只支持python 2.7。要支持3.7需要自行修改部分代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"slsters"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 下午2:16
收件人:&nbsp;"flashlxy/PyMICAPS"<PyMICAPS@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[flashlxy/PyMICAPS] 运行报错 (#14)




python环境3.7
 报错信息
 $ python main.py config.xml
 Traceback (most recent call last):
 File "main.py", line 13, in 
 reload(sys)
 NameError: name 'reload' is not defined

**Comment by Liquid-Zhangliquan** [comment]
> 仔细查看项目环境，只支持python 2.7。要支持3.7需要自行修改部分代码
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"slsters"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月15日(星期五) 下午2:16 收件人:&nbsp;"flashlxy/PyMICAPS"<PyMICAPS@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[flashlxy/PyMICAPS] 运行报错 (#14) python环境3.7 报错信息 $ python main.py config.xml Traceback (most recent call last): File "main.py", line 13, in reload(sys) NameError: name 'reload' is not defined — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好吧，我先切换python环境，谢谢解答
